'use client';
import {site} from './config'; import {useEffect,useState} from 'react';
const Arrow=()=> <span aria-hidden>↗</span>;
export default function Page(){const [menu,setMenu]=useState(false); useEffect(()=>{const cleanups:Array<()=>void>=[]; const media=window.matchMedia('(min-width: 761px)'); document.querySelectorAll<HTMLElement>('.areaGrid').forEach(track=>{const onWheel=(event:WheelEvent)=>{if(!media.matches||track.scrollWidth<=track.clientWidth+2||Math.abs(event.deltaY)<=Math.abs(event.deltaX))return; const rect=track.getBoundingClientRect(); if(rect.top<-24||rect.bottom>window.innerHeight+24)return; const max=track.scrollWidth-track.clientWidth; const movingRight=event.deltaY>0; const canMove=movingRight?track.scrollLeft<max-1:track.scrollLeft>1; if(!canMove)return; event.preventDefault(); track.scrollBy({left:event.deltaY,behavior:'auto'})}; track.addEventListener('wheel',onWheel,{passive:false}); cleanups.push(()=>track.removeEventListener('wheel',onWheel))}); const reduce=window.matchMedia('(prefers-reduced-motion: reduce)').matches; if(!reduce){const observer=new IntersectionObserver((entries)=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('inview'); observer.unobserve(entry.target)}})},{threshold:.4}); document.querySelectorAll<HTMLElement>('.partners,.goldLine').forEach(el=>observer.observe(el)); cleanups.push(()=>observer.disconnect())} else {document.querySelectorAll<HTMLElement>('.partners,.goldLine').forEach(el=>el.classList.add('inview'))} return()=>{cleanups.forEach(fn=>fn())}},[]); const wa=site.whatsapp?`https://wa.me/${site.whatsapp}?text=${encodeURIComponent('Olá! Gostaria de agendar uma conversa com '+site.name+'.')}`:site.map; const cta=site.whatsapp?'Fale com o escritório':'Ver contato no Google'; return <main className={`theme-${site.theme}`}>
 <header><a className="brand" href="#inicio"><img src="/logo.png" alt={site.name} className="brandLogo"/><span>{site.short}</span></a><button className="menu" onClick={()=>setMenu(!menu)} aria-expanded={menu} aria-controls="nav" aria-label={menu?'Fechar menu':'Abrir menu'}>{menu?'Fechar':'Menu'}</button><nav id="nav" className={menu?'open':''} aria-label="Navegação principal"><a href="#atuacao" onClick={()=>setMenu(false)}>Atuação</a><a href="#socios" onClick={()=>setMenu(false)}>Sócios</a><a href="#contato" onClick={()=>setMenu(false)}>Contato</a><a className="navCta" href={wa}>Agendar <Arrow/></a></nav></header>
 <section className="hero" id="inicio"><img src={site.image} alt="Os três sócios de Lima Lopes e Diógenes Advogados" fetchPriority="high"/><div className="veil"/><div className="heroCopy reveal"><small>{site.kicker}</small><h1>{site.title}</h1><p>{site.intro}</p><div className="partners" aria-label="Sócios do escritório"><span>LIMA</span><b>·</b><span>LOPES</span><b>·</b><span>DIÓGENES</span></div><div className="actions"><a className="primary" href={wa}>{cta} <Arrow/></a><a className="textLink" href="#atuacao">Conheça a atuação ↓</a></div></div><div className="sideNote">PARAUAPEBAS · PARÁ</div><div className="scroll">Role para descobrir</div></section>
 <section className="manifest reveal"><span>01 · NOSSA VISÃO</span><blockquote>“{site.quote}”</blockquote></section>
 <section className="areas" id="atuacao"><div className="sectionHead reveal"><span>02 · ÁREAS DE ATUAÇÃO</span><div className="goldLine"/><h2>Direito explicado<br/>com clareza.</h2><p>Cada demanda começa com escuta atenta, análise responsável e orientação objetiva sobre os caminhos possíveis.</p></div><div className="areaGrid">{site.areas.map((a,i)=><article className="reveal" key={a[0]}><i>0{i+1}</i><h3>{a[0]}</h3><p>{a[1]}</p><Arrow/></article>)}</div></section>
 <section className="about" id="socios"><div className="aboutVisual reveal"><img src="/detail.jpg" alt="Dra. Karolline Diógenes, sócia" loading="lazy" decoding="async"/><div className="portraitCaption"><b>Dra. Karolline Diógenes</b><small>SÓCIA</small></div><div className="stamp">{site.monogram}<small>PARAUAPEBAS · PA</small></div></div><div className="aboutCopy reveal"><span>03 · A SOCIEDADE</span><div className="goldLine"/><h2>Três sócios.<br/>Uma só direção.</h2><p>{site.about}</p><ul>{site.values.map(v=><li key={v}><b>✓</b>{v}</li>)}</ul><a className="textLink" href={wa}>Converse sobre seu caso <Arrow/></a></div></section>
 <section className="process"><div className="sectionHead reveal"><span>04 · COMO TRABALHAMOS</span><div className="goldLine"/><h2>Três olhares sobre<br/>cada caso.</h2></div><div className="steps"><article><b>01</b><h3>Lima</h3><p>Uma perspectiva técnica sobre cada detalhe do caso, antes de qualquer decisão.</p></article><article><b>02</b><h3>Lopes</h3><p>Uma segunda leitura, atenta aos riscos e às alternativas possíveis.</p></article><article><b>03</b><h3>Diógenes</h3><p>Condução próxima do cliente, do primeiro contato à última palavra.</p></article></div></section>
 <section className="contact" id="contato"><div className="contactTitle reveal"><small>05 · CONTATO</small><h2>Vamos conversar?</h2><p>Agende uma conversa inicial para apresentar sua demanda ao escritório.</p><a className="primary light" href={wa}>{cta} <Arrow/></a></div><div className="contactInfo reveal"><div><small>ENDEREÇO</small><p>{site.address}</p><a href={site.map}>Ver no Google Maps <Arrow/></a></div><div><small>TELEFONE</small><p>{site.phone}</p></div>{site.instagram&&<div><small>INSTAGRAM</small><a href={site.instagram}>Acessar perfil <Arrow/></a></div>}</div></section>
 <footer><div className="brand"><img src="/logo.png" alt={site.name} className="brandLogo"/><span>{site.short}</span></div><p>Conteúdo informativo. Cada situação jurídica exige análise individual.</p><span>© 2026 {site.short}</span></footer>{site.whatsapp&&<a className="whatsapp" href={wa} aria-label="Falar pelo WhatsApp">WhatsApp</a>}
 </main>}
